### ISSUE TITLE
Suggestion for Footer Links

### ISSUE THREAD

**Issue by LoganVance** [engl-4814/html-review#20]
https://github.com/engl-4814/html-review/blob/4b061905e974a46420013469bfb51f5ac08476eb/block/concepts/head.html#L176-L180
@chaitrakatragadda 
I feel like it would be best to use an href to have text that links to the website, instead of just having a direct link. For example, for the first one, you could put <a href='https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML'>What’s in the head? Metadata in HTML via Mozilla Developer Network</a>. This way you'll have the title of the actual article and the website name show, instead of just a hyper link.
This was the only issue I saw, it looks good otherwise!

**Comment by chaitrakatragadda** [comment]
Thanks for the suggestion. We reviewed and made changes as suggested.
