### ISSUE TITLE
Question about accessibility section

### ISSUE THREAD

**Issue by kthibner** [engl-4814/html-review#3]
https://github.com/engl-4814/html-review/blob/159687b2d8c089f429ee8af1c8f07dd0bd8c1a40/inline/a.html#L127

@karthikagnihotri These are considerations I didn't know about, so thank you for including them. You say that we should indicate what will happen if its an external link or download link, so how would you indicate that?

**Comment by karthikagnihotri** [comment]
Hi @kthibner , that's a good question. We can indicate what will happen if the link opens in an external window by adding alt text after the link. I have linked an example to the hyperlinks I updated on the `a` page.

https://github.com/engl-4814/html-review/blob/d16ef55b72b48a8dd40660b9f28cf689f18ff2ba/inline/a.html#L159
